news_project/urls.py
from django.conf.urls import url
from django.contrib import admin
import db.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', db.views.index, name='index'),
    url(r'^tags/$', db.views.tags, name='tags'),
    url(r'^tags/daily$', db.views.tags, {'daily': True}, name='tags'),
    url(r'^tags/(?P<key_list>(\w|\+)+)/$', db.views.tag_detail, name='tag_detail'),
    url(r'^news/id(?P<news_id>[0-9]+)/$', db.views.news_detail, name='tag_detail'),
    url(r'^news2/id(?P<news_id>[0-9]+)/$', db.views.new_news_detail, name='new_news_detail'),
    url(r'^news/day/$', db.views.news_per_day, name='tag_detail'),
    url(r'^main/$', db.views.main_page, name='main_page'),
    url(r'^news3/id(?P<news_id>[0-9]+)/$', db.views.news3_detail, name='news3_detail'),
    url(r'^news3/id(?P<news_id>[0-9]+)/related_news', db.views.related_news_json, name='related_news_json'),
    url(r'^news_theme/$', db.views.news_theme, name='news_theme'),
]

db/models.py
from django.db import models


class Site(models.Model):
    name = models.CharField(max_length=100)


class News(models.Model):
    related_news = models.ManyToManyField("self")
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    url = models.URLField(max_length=255, unique=True)
    pub_date = models.DateTimeField('date published', db_index=True)
    summary = models.TextField(blank=True, null=True)
    is_parsed = models.BooleanField('text was parsed?', default=False, db_index=True)


class RssChannels(models.Model):
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    url = models.URLField(max_length=300)


class AllTags(models.Model):
    tag = models.CharField(max_length=20, unique=True)


class NewsText(models.Model):
    news = models.OneToOneField(
        News,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    text = models.TextField()
    is_keywords_extracted = models.BooleanField(default=False, db_index=True)
    is_parsed = models.BooleanField(default=False)
    check_tag = models.BooleanField(default=False, db_index=True)
    is_emo_defined = models.BooleanField(default=False, db_index=True)
    is_vectorized = models.BooleanField(default=False, db_index=True)
    tags = models.ManyToManyField(AllTags, through='NewsTags')


class KeyWord(models.Model):
    news = models.ManyToManyField(News)
    word = models.CharField(max_length=100, unique=True)


# TODO переделать связь на News
class NewsTags(models.Model):
    news = models.ForeignKey(NewsText, on_delete=models.CASCADE)
    tag = models.ForeignKey(AllTags, on_delete=models.CASCADE)
    weight = models.DecimalField(max_digits=6, decimal_places=3)


# TODO переделать связь на News
class NewsEmotions(models.Model):
    news = models.OneToOneField(
        NewsText,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    emo_weight = models.DecimalField(max_digits=5, decimal_places=4)


class ASources(models.Model):
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    url = models.URLField(max_length=300)


class UrlInText(models.Model):
    news = models.ManyToManyField(
        News)
    url = models.URLField(max_length=300, db_index=True)


class NewsVector(models.Model):
    news = models.OneToOneField(
        News,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    vector = models.BinaryField(null=True)
    is_compared = models.BooleanField(default=False, db_index=True)

db/views.py
import itertools

from django.core.paginator import Paginator
from django.db.models import Count, Max, Min, F, DecimalField, ExpressionWrapper
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

from db.models import *

MAX_RETURN = 5
MIN_RETURN = 1


def trivial_abs(value, max_v, min_v):
    return (value - min_v - 0.0) / (max_v - min_v) * (MAX_RETURN - MIN_RETURN) + MIN_RETURN


def index(request):
    if 'json1' in request.GET:
        from django.db.models import Count
        news = News.objects \
            .extra({'y': 'strftime("%Y-%m-%d-%H",pub_date)'}) \
            .values('y') \
            .annotate(cnt=Count('pub_date'))
        return JsonResponse([n for n in news if "2016-04-24-02" < n['y'] < "2016-05-01-02"], safe=False)
    if 'json2' in request.GET:
        from django.db.models import Count
        news = News.objects \
            .extra({'y': 'date(pub_date)'}) \
            .values('y') \
            .annotate(cnt=Count('pub_date')) \
            .annotate(i=Min('id'))

        resp_dict = list()
        for n in news:
            first_day_news = News.objects.get(id=n['i'])
            n["n"] = first_day_news.title
            resp_dict.append(n)

        return JsonResponse(resp_dict, safe=False)
    context = {}
    return render(request, 'db/index2.html', context)


def tags(request, daily=False):
    key_query = KeyWord.objects
    if daily:
        key_query = key_query.filter(news__pub_date__day=15, news__pub_date__month=4)
        key_query = key_query.annotate(cnt=Count('news'))
    else:
        key_query = key_query.annotate(cnt=Count('news')).filter(cnt__gt=1000)[:150]
    key_range = key_query.aggregate(max=Max('cnt'), min=Min('cnt'))
    context = {"key": key_query.annotate(cnt_n=ExpressionWrapper(
        trivial_abs(F('cnt'), key_range['max'], key_range['min']), output_field=DecimalField(decimal_places=1)))}
    return render(request, 'db/tags.html', context)


def tag_detail(request, key_list=''):
    key_list = key_list.split('+')
    news = News.objects
    for key in key_list:
        if not key: continue
        news = news.filter(keyword__word=key)
    context = {"news_list": news, "key_list": key_list}
    return render(request, 'db/key_list.html', context)


def news_detail(request, news_id=0):
    news = get_object_or_404(News, pk=news_id)
    context = {"news": news}
    return render(request, 'db/news.html', context)


def new_news_detail(request, news_id=0):
    if 'json' in request.GET:
        news = News.objects.get(pk=news_id)
        return JsonResponse([{"id": n.pk, "date": n.pub_date} for n in news.related_news.iterator()], safe=False)

    news = get_object_or_404(News, pk=news_id)
    context = {"news": news}
    return render(request, 'db/news2.html', context)


def news_per_day(request):
    news = News.objects
    if "related_news" in request.GET:
        news = news.get(pk=request.GET["related_news"]).related_news
    if "day" in request.GET:
        news = news.filter(pub_date__day=request.GET["day"])
    if "month" in request.GET:
        news = news.filter(pub_date__month=request.GET["month"])
    context = {"news_list": news, "key_list": [1,2]}
    return render(request, 'db/key_list.html', context)


def main_page(request):
    all_news = News.objects.all()
    paginator = Paginator(all_news, 6)
    page = request.GET.get('page', 1)
    news_list = paginator.page(page)
    # news = []
    # for i in range(7,13):
    #     news.append(News.objects.get(pk=i))
    context = {"news": news_list, "paginator": paginator}
    return render(request, 'db/main_page.html', context)


def news3_detail(request, news_id=0):
    news = get_object_or_404(News, pk=news_id)
    if news.newstext.is_emo_defined:
        emo = news.newstext.newsemotions.emo_weight
    else:
        emo = 0
    context = {"news": news, "emo": emo}
    return render(request, 'db/news3.html', context)


def related_news_json(request, news_id=0):
    main_news = get_object_or_404(News, pk=news_id)
    related_news = {"name": main_news.title, "children": []}
    for news in main_news.related_news.all():
        related_news_info = {"name": news.title, "size": 6714}
        related_news["children"].append(related_news_info)
    # main_news = get_object_or_404(News, pk=news_id)
    # related_news = {
    #      "name": main_news.title,
    #       "children": [
    #            {"name": "AgglomerativeCluster", "size": 10000},
    #            {"name": "CommunityStructure", "size": 10000},
    #            {"name": "HierarchicalCluster", "size": 10000},
    #            {"name": "MergeEdge", "size": 10000}
    #             ]
    #         }
    return JsonResponse(related_news)


def news_theme(request):
    all_news = News.objects.all()
    paginator = Paginator(all_news, 6)
    page = request.GET.get('page', 1)
    news_list = paginator.page(page)

    news_count = News.objects.count()
    all_news = News.objects.order_by('pub_date').all()
    sites_info = []
    all_sites = Site.objects.all()
    for current_site in all_sites:
        current_site_info = []
        current_site_info.append(current_site.name)
        news_per_site = all_news.filter(site__name=current_site.name).count()
        current_site_info.append(news_per_site*100//news_count)
        sites_info.append(current_site_info)

    emotions = [['Позитивные'], ['Негативные'], ['Нейтральные']]
    good_news_pers = (all_news.filter(newstext__newsemotions__emo_weight__gte=0.5).count()/news_count)*100
    normal_news_pers = (all_news.filter(newstext__newsemotions__emo_weight__lte=0.2).count()/news_count)*100
    emotions[0].append(good_news_pers)
    emotions[1].append(100 - good_news_pers - normal_news_pers)
    emotions[2].append(normal_news_pers)

    first_char_in_dates = ['x']
    dates = []
    news_count_per_day_1 = ['Количество новостей за последние дни']
    news_count_per_day = []
    # for key, group in itertools.groupby(all_news, key=lambda x: str(x.pub_date.date())):
    #     dates.append(str(key))
    #     news_count_per_day.append(len(list(group)))

    from django.db.models import Count
    news = News.objects \
        .extra({'y': 'date(pub_date)'}) \
        .values('y') \
        .annotate(cnt=Count('pub_date')) \

    for n in news:
        dates.append(str(n['y'].strftime("%Y-%m-%d")))
        news_count_per_day.append(n['cnt'])

    full_dates = first_char_in_dates + dates[-6:]
    news_count_per_day_full = news_count_per_day_1 + news_count_per_day[-6:]

    context = { 'news': news_list,
                'news_count': news_count,
                'news_dates': full_dates,
                'news_count_per_day': news_count_per_day_full,
                'sites_info': sites_info,
                'emotions': emotions,
                }
    # print(report)
    return render(request, 'db/news_theme.html', context)

db/templates/db/index2.html
<html>

<head>
    <link rel="stylesheet" href="/static/db/index.css" type="text/css">
    <script src="//d3js.org/d3.v3.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:300|Didact+Gothic|Marmelad|Tenor+Sans&subset=latin,cyrillic'
        rel='stylesheet' type='text/css'>
</head>

<body>
    <div class="main">
        <div class="menu">
            <div class="item">
                аналитика за период
            </div>
            <div class="item">
                новостные темы
            </div>
            <div class="item">
                категории
            </div>
            <div class="item">
                <a href="/tags" class="link">
                    ключевые слова
                </a>
            </div>

            <div class="item">
                что это?
            </div>
        </div>
        <div class="timeline" onmousedown="event.preventDefault ? event.preventDefault() : event.returnValue = false">
        </div>
    </div>
    <script src="/static/db/timeline.js"></script>
</body>

</html>

db/templates/db/key_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        p {
            text-align:center;
        }
        a {
            text-decoration: none;
            color:black;
        }
        a:hover {
            color:#484959;
        }

    </style>
</head>
<body>
<h1>
    {% for key in key_list %}
        _ {{ key }} _
    {% endfor %}
</h1>
<ul>
{% for news in news_list.all %}
    <li><a href="/news/id{{ news.id }}">{{ news.site.name}} - {{ news.title }} </a> </li>
{% endfor %}
</ul>
</body>
</html>

db/templates/db/main_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>NewsGear</title>

    <!-- Custom styles for this template -->
    <link href="offcanvas.css" rel="stylesheet">

      <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/main">NewsGear
          <a class="navbar-brand" href="/news_theme">News Info</a>
    </nav><!-- /.navbar -->

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>NewsGear</h1>
            <p>Аналитический новостной портал</p>
          </div>
          <div class="row">
              {% for current_news in news %}
                  <div class="col-xs-6 col-lg-4">
                    <h2>{{current_news.title}}</h2>
                    <p><a class="btn btn-default" href="/news3/id{{ current_news.id }}" role="button">View details &raquo;</a></p>
                  </div><!--/.col-xs-6.col-lg-4-->
              {% endfor %}
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->
      </div><!--/row-->

      <hr>

      <nav>
          <ul class="pager">
              {% if news.has_previous %}
                  <li class="pager-prev"><a href="?page={{ news.previous_page_number }}">Previous</a></li>
              {% endif %}

              {% if news.has_next %}
                  <li class="pager-next"><a href="?page={{ news.next_page_number }}">Next</a></li>
              {% endif %}
          </ul>
      </nav>

      <footer>
        <p>&copy; 2016 NewsGear</p>
      </footer>

    </div><!--/.container-->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="/static/db/offcanvas.js"></script>
  </body>
</html>

db/templates/db/news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ news.title }}</title>
    <style>
        a {
            text-decoration: none;
            color:black;
        }
        a:hover {
            color:#484959;
        }

    </style>
</head>
<body>
<h2>{{ news.site.name }}</h2>
<h1>{{ news.title }}</h1>
<p>{{ news.newstext.text }}</p>
<a href="{{ news.url }}">{{ news.url }}</a>
<br>
{% if news.keyword_set %}
<h3> Keywords</h3>
<p>
    {% for k in news.keyword_set.all %}
    <a href="/tags/{{ k.word }}">
        <span style="font-size:{{ k.cnt_n }}em">{{ k.word }}</span>
    </a>
    {% endfor %}
</p>
{% endif %}
{% if news.urlintext_set.exists %}
<h3> Url in text</h3>
<ul>
    {% for url in news.urlintext_set.all %}
    <li><a href="{{ url.url }}">{{ url.url }}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% if news.newstext.newstags_set.exists %}
<h3> Tags </h3>
<ul>
    {% for tag in news.newstext.newstags_set.all %}
    <li>{{ tag.tag.tag }} {{ tag.weight }}</li>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>

db/templates/db/news2.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <link rel="stylesheet" href="/static/db/news.css" type="text/css">
    <script src="//d3js.org/d3.v3.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <script>var emoWeight = {{ news.newstext.newsemotions.emo_weight }}, newsId = {{ news.pk }};</script>
</head>

<body>
    <div class="main">
        <div class="container">
            <div class="news">
                <div class="tags">
                    {% if news.newstext.newstags_set.exists %}
                        {% for tag in news.newstext.newstags_set.all %}
                            <span class="cu_tag">{{ tag.tag.tag.upper }}</span> 
                        {% endfor %} 
                    {% endif %}
                </div>
                <div class="news_text">
                    <h2>{{ news.site.name }}</h2>
                    <h1>{{ news.title }}</h1>
                </div>
                <div class="keys">
                    {% if news.keyword_set %}
                        {% for k in news.keyword_set.all %}
                            <a href="/tags/{{ k.word }}">
                                <span style="font-size:{{ k.cnt_n }}em">{{ k.word }}</span>
                            </a>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="svg"></div>
        </div>
    </div>
    <script src="/static/db/news.js"></script>
</body>

</html>

db/templates/db/news3.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>NewsGear</title>

      <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">


     <style>

    .node circle {
      cursor: pointer;
      stroke: #3182bd;
      stroke-width: 1.5px;
    }

    .node text {
      font: 12px sans-serif;
      pointer-events: none;
      text-anchor: middle;
    }

    line.link {
      fill: none;
      stroke: #9ecae1;
      stroke-width: 5px;
    }

    </style>
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/main">NewsGear</a>
          <a class="navbar-brand" href="/news_theme">News Info</a>
    </nav><!-- /.navbar -->

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-12">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <div class="row">
                <div class="col-md-11"><h1>{{ news.title }}</h1></div>
                {% if emo > 0.5 %}
                    <div class="col-md-1 "><h3><span class="label label-success">Good</span></h3></div>
                {% elif emo < 0.2%}
                    <div class="col-md-1 "><h3><span class="label label-danger">Bad</span></h3></div>
                {% else %}
                    <div class="col-md-1 "><h3><span class="label label-warning">Normal</span></h3></div>
                {% endif %}
            </div>
              <div class="row">
                <div class="col-md-4"><p class="text-left"><a href={{ news.url }}>{{ news.site.name }}</a></p></div>
                <div class="col-md-4">
                    <h2>
                    {% for tag in news.newstext.tags.all %}
                        /{{ tag.tag }}
                    {% endfor %}/
                    </h2>
                </div>
{#                <div class="col-md-4 col-md-offset-4">.col-md-4 .col-md-offset-4</div>#}
                <div class="col-md-4"><p class="text-right">{{ news.pub_date| date }}</p></div>
            </div>
          </div>
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

      </div><!--/row-->


{#    <div class="row">#}
{#        {% for tag in news.related_news.all %}#}
{#            <div class="col-md-4">{{ tag.title }}</div>#}
{#        {% endfor %}#}
{#    </div><!--/row-->#}

    <xz></xz>
    <hr>

      <footer>
        <p>&copy; 2016 NewsGear</p>
      </footer>

    </div><!--/.container-->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
{#    <script src="/static/offcanvas.js"></script>#}
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="/static/db/jchart.js"></script>
{#    <script>#}
{#        $(document).ready(function() {#}
{#            $("#bar_of_pies").jChart();#}
{#        });#}
{#    </script>#}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.js"></script>
    <script src="//d3js.org/d3.v3.min.js"></script>
    <script>
        var width = 1500,
        height = 1000,
        root;

        var force = d3.layout.force()
            .linkDistance(350)
            .charge(-120)
            .gravity(.01)
            .size([width, height])
            .on("tick", tick);

        var svg = d3.select("xz").append("svg")
            .attr("width", width)
            .attr("height", height);

        var link = svg.selectAll(".link"),
            node = svg.selectAll(".node");

        d3.json("related_news", function(error, json) {
          if (error) throw error;

          root = json;
          update();
        });

        function update() {
          var nodes = flatten(root),
              links = d3.layout.tree().links(nodes);

          // Restart the force layout.
          force
              .nodes(nodes)
              .links(links)
              .start();

          // Update links.
          link = link.data(links, function(d) { return d.target.id; });

          link.exit().remove();

          link.enter().insert("line", ".node")
              .attr("class", "link");

          // Update nodes.
          node = node.data(nodes, function(d) { return d.id; });

          node.exit().remove();

          var nodeEnter = node.enter().append("g")
              .attr("class", "node")
              .on("click", click)
              .call(force.drag);

          nodeEnter.append("circle")
                .attr("r", function(d) { return 20; });


{#          nodeEnter.append("text")#}
{#              .attr("dy", ".35em")#}
{#              .text(function(d) { return d.name; });#}

          nodeEnter.append("a")
              .attr("xlink:href", "/main/?page=2")
              .append("text")
              .attr("dy", ".35em")
              .text(function(d) { return d.name; });

          node.select("circle")
              .style("fill", color);
        }

        function tick() {
          link.attr("x1", function(d) { return d.source.x; })
              .attr("y1", function(d) { return d.source.y; })
              .attr("x2", function(d) { return d.target.x; })
              .attr("y2", function(d) { return d.target.y; });

          node.attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });
        }

        function color(d) {
          return d._children ? "#3182bd" // collapsed package
              : d.children ? "#c6dbef" // expanded package
              : "#f0ad4e"; // leaf node
        }

        // Toggle children on click.
        function click(d) {
          if (d3.event.defaultPrevented) return; // ignore drag
          if (d.children) {
            d._children = d.children;
            d.children = null;
          } else {
            d.children = d._children;
            d._children = null;
          }
          update();
        }

        // Returns a list of all nodes under the root.
        function flatten(root) {
          var nodes = [], i = 0;

          function recurse(node) {
            if (node.children) node.children.forEach(recurse);
            if (!node.id) node.id = ++i;
            nodes.push(node);
          }

          recurse(root);
          return nodes;
        }

    </script>
  </body>
</html>

db/templates/db/tags.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tags</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:300|Didact+Gothic|Marmelad|Tenor+Sans&subset=latin,cyrillic'
          rel='stylesheet' type='text/css'>
    <style>

        * {
            margin: 0;
            font-family: "Roboto Slab";
            color: #00173e;

        }
        p {
            text-align:center;
        }
        a {
            text-decoration: none;
            color:black;
        }
        a:hover {
            color:#484959;
        }


    </style>
</head>
<body>

<p>
    {% for k in key %}
    <a href="{{ k.word }}">
        <span style="font-size:{{ k.cnt_n }}em">{{ k.word }}</span>
    </a>
    {% endfor %}
</p>
</body>
</html>